[project]
name = "lite-forks-app"
version = "0.1.0"
description = "Vercel deployment for forks app"
requires-python = ">=3.11"

[project.dependencies]
Flask
# Можно просто Flask = "*" если не хотите указывать конкретную версию

[tool.uv]